name: Build Cross-Platform

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Build macOS
      run: |
        cd macos
        xcodebuild -project Opra.xcodeproj \
          -scheme Opra \
          -configuration Release \
          -derivedDataPath build \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGN_ENTITLEMENTS="" \
          CODE_SIGNING_ALLOWED=NO \
          clean build
        cd ..
    
    - name: Upload macOS App
      uses: actions/upload-artifact@v4
      with:
        name: opra-macos
        path: macos/build/Build/Products/Release/Opra.app
        retention-days: 30

  build-windows:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2
    
    - name: Restore Windows dependencies
      run: |
        dotnet restore windows/Opra/Opra.csproj
    
    - name: Build Windows
      run: |
        msbuild windows/Opra.sln -p:Configuration=Release -p:Platform=x64 -p:AppxPackageSigningEnabled=false -p:UapAppxPackageBuildMode=SideloadOnly
    
    - name: Upload Windows App
      uses: actions/upload-artifact@v4
      with:
        name: opra-windows
        path: windows/Opra/bin/x64/Release/
        retention-days: 30